
azure:
  keyvault:
    enabled: true
    uri: https://op-key.vault.azure.net
    client-id: 22bcecb1-6955-426a-a660-cca1fc193e64
    client-key: 0pU8Q~HaBBD_~_fmZeSRO9mF-9aq8s9.jTw9sc_y
    tenant-id: 6d4b49a0-7ac2-4821-9872-c20ce31c3f0d

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBUrl}
    username: ${UserDB}
    password: ${DBPass}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    spring.jpa.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9191  
  
  


  


