spring:
  datasource:
    url: jdbc:sqlserver://onepiece-tcg-db.database.windows.net:1433;database=onepiece;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: aleyah96
    password: CiccioJuve69!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect


server:
  port: 9191  


